### PR TITLE
#3 Fixes tests for Django 1.10

### PR DESCRIPTION
**Pull request by dnmellen**

### CODE REVIEW

**Comment by aniketmaithani** [comment]
@dnmellen This looks good. :+1:

**Comment by aniketmaithani** [comment]
@dnmellen I've been using this project of yours. Can you merge this PR? Will make things easy for the devs around :)

**Comment by dnmellen** [comment]
Sorry @aniketmaithani, I have no control of that repository anymore

**Comment by Disruption** [comment]
@aniketmaithani 
I merged it since everything looks ok. Sorry for not having seen this earlier, we don't use lilliput anymore on our side, so this repository was a bit aside from the ones we check regularly.

@dnmellen  Thanks for the reply that gave us a headsup!

**Pull request merged**
